name: CI

on: [push, pull_request]

env:
  HTTPTOOLKIT_SERVER_DISABLE_AUTOUPDATE: 1

jobs:
  build-and-publish-windows:
    name: Build & Publish Windows Release
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.1

      - run: npm install -g npm@^8

      - run: npm ci
        env:
          NPM_CONFIG_UNSAFE_PERM: true

      - run: npm run build:src

      - run: npm run build:release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.TOKEN || '' }}
          SENTRY_ORG: http-toolkit
          SENTRY_PROJECT: httptoolkit-server
          NPM_CONFIG_UNSAFE_PERM: true

      - uses: actions/upload-artifact@v4
        with:
          name: distributables
          path: build/dist/*
          if-no-files-found: error

      - name: Publish a release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: build/dist/*/*
          file_glob: true
          tag: ${{ github.ref }}
